name: LLM Lab Mistral 7B Standalone Model Deployment
description: "TBD"
author: "Cloudera"
date: "2023-11-26"
specification_version: 1.0
prototype_version: 1.0
environment_variables:
  

runtimes: 
  - editor: JupyterLab
    kernel: Python 3.10
    edition: Nvidia GPU
  
tasks:
  - type: run_session
    name: Install Dependencies
    script: 0_install_prerequisites/download_reqs_set_vars.py
    short_summary: Install Dependencies
    kernel: python3
    cpu: 2
    memory: 12

  - type: create_job
    name: Pull and Convert HTMLS to TXT
    entity_label: htmls_to_txt
    script: 2_create_knowledge_base/html_to_text.py
    arguments: None
    short_summary: Create job to source htmls, download, and convert them to text. 
    long_summary: Create job to source htmls, download, and convert them to text. Update html_links.txt with the htmls you wish to download and convert.
    cpu: 2
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_session
    name: Setup Chroma Server
    script: 0_install_prerequisites/setup-chroma.py
    short_summary: Setup Chroma Server Vector DB
    long_summary: Resolve sqlite dependency with python version and control logging in Chroma server package
    kernel: python3
    cpu: 2
    memory: 4

  - type: create_job
    name: Populate Chroma Vector DB with document embeddings
    entity_label: chroma_vectordb_insert
    script: 3c_load_to_chroma_vector_db/populate_chroma_vectors.py
    arguments: None
    short_summary: Create job to push vectors with document embeddings to Chroma DB. 
    cpu: 2
    memory: 4
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: start_application
    name: CML Chroma Server REST API Server
    subdomain: cml-chroma-server
    script: 3c_load_to_chroma_vector_db/launch-server.py
    short_summary: Launch Chroma Server
    long_summary: Launch Chroma Server REST API application. Vector Database creates encodings for GET and POST requests. Remember to enable unauthenticated app access for external access to the UI.
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION